server:
  port: 9001
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/favorites_center?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: crwen469612
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd

  mail:
    host: smtp.qq.com
    username: 1543720935@qq.com
    password: opwuawvtybegjhji
    default-encoding: UTF-8
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
            socketFactory:
              port: 465
              class: javax.net.ssl.SSLSocketFactory
    protocol: smtp

  redis:
    database: 0
    host: 139.9.138.56
    port: 6379
    password: crwen469612
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 1000


mail:
  fromMail:
    sender: 1543720935@qq.com
    receiver: 547767973@qq.com
